"""知识库写入：在源目录下生成 knowledge/ 目录。"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

from .config import Config
from .models import Chunk

README_TEMPLATE = """# Knowledge Base Usage Guide (generated by the knowledge-summary kernel)

This directory summarizes and indexes the source content for two purposes:
1. **Overall understanding**: quickly grasp the topics, structure and key points of the summarized content.
2. **Locating**: find the exact position in the source files for a given question, then read the original text.

## Files and reading order

| File | Content | When to read |
|---|---|---|
| `01_overview.md` | Global overview: topics, module responsibilities, dependencies | **Read this first** |
| `02_summary.md` | Hierarchical summary (global / file-level / chunk-level) | When you need details |
| `03_topology.json` | Entity and relation graph (every entry carries a source pointer) | To understand inter-module dependencies |
| `04_locate_index.json` | Locate index: entity/keyword -> exact source location | When answering a specific question |
| `chunks/` or `chunks_bundle.md` | Chunk source text + chunk summaries | When you need nearby context |
| `manifest.json` | Generation metadata, config fingerprint, statistics | To check whether the knowledge is stale |

## Recommended answering flow (for LLMs reading this directory)

1. Read `01_overview.md` first to build a global understanding.
2. For the user's question, look up the relevant entity names / keywords in `04_locate_index.json`.
3. The `file` + `line_start`~`line_end` (or `page_start`~`page_end`) fields in an index entry point to the exact location in the source file.
4. If needed, go back to the source file and read the original text at the pointer; `chunks/` keeps the chunk-level source as nearby context.
5. The `span` field in `03_topology.json` also carries source pointers and can be cross-checked.

## Source content

- Source root: `{source_root}`
- Files: {file_count}, chunks: {chunk_count}
- Generated at: {generated_at}

> Note: if the source files have changed, this knowledge base may be stale — re-run the kernel to regenerate it.
"""


def write_knowledge(out_dir: Path, payload: Dict[str, Any], cfg: Config) -> None:
    """payload 键: manifest, overview, summary, topology, locate_index, chunks, source_root"""
    out_dir.mkdir(parents=True, exist_ok=True)
    write_chunks = cfg.get("storage", "write_chunks", True)
    max_chunk_files = int(cfg.get("storage", "max_chunk_files", 500))

    (out_dir / "00_README.md").write_text(
        README_TEMPLATE.format(
            source_root=payload["source_root"],
            file_count=payload["manifest"]["stats"]["files"],
            chunk_count=payload["manifest"]["stats"]["chunks"],
            generated_at=payload["manifest"]["generated_at"],
        ),
        encoding="utf-8",
    )
    (out_dir / "01_overview.md").write_text(payload["overview"], encoding="utf-8")
    (out_dir / "02_summary.md").write_text(payload["summary"], encoding="utf-8")

    _write_json(out_dir / "03_topology.json", payload["topology"])
    _write_json(out_dir / "04_locate_index.json", payload["locate_index"])

    chunks: List[Chunk] = payload["chunks"]
    if write_chunks and chunks:
        if len(chunks) <= max_chunk_files:
            chunk_dir = out_dir / "chunks"
            chunk_dir.mkdir(exist_ok=True)
            for c in chunks:
                (chunk_dir / f"{c.id}.md").write_text(_chunk_md(c), encoding="utf-8")
        else:
            parts = [f"# Chunk source bundle (total {len(chunks)} chunks, merged because the single-file limit was exceeded)\n"]
            for c in chunks:
                parts.append(_chunk_md(c))
                parts.append("\n---\n")
            (out_dir / "chunks_bundle.md").write_text("".join(parts), encoding="utf-8")

    (out_dir / "manifest.json").write_text(
        json.dumps(payload["manifest"], ensure_ascii=False, indent=2), encoding="utf-8")


def _chunk_md(c: Chunk) -> str:
    lines = [
        f"# {c.id}",
        f"- Source: `{c.span.rel_path}`",
        f"- Location: {c.span.display()}",
    ]
    if c.summary:
        lines.append("\n## Summary\n" + c.summary)
    lines.append("\n## Source text\n```\n" + c.text + "\n```")
    return "\n".join(lines)


def _write_json(path: Path, data: Any) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def now_iso() -> str:
    return datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")
